print("Hello, my name is Jackson Calvert and I am a Sophomore English major.")
print("Reading has always been a passion, I most recently started 'Infinte Jest' by David Foster Wallace.")
print("I have two dogs, Hank and Otis, and two cats, Max and Ruby.")
print("I have experience with computer hardware, but little to none in software.")
print("My recent favorite activity is amatuer armchair philosophy about global trends.")